from PyQt6 import QtWidgets, QtCore, QtGui
from PyQt6.QtWidgets import QMessageBox

class TelaAbastecimento():
  def __init__(self):
    self.inputBomba = None
    self.inputTipo = None
    self.inputPreco = None
    self.inputLitros = None
    self.confirmarBtn = None
    self.cancelarBtn = None
    self.cria_tela(self)

  def mostra_mensagem(self, mensagem: str) -> None:
    QMessageBox.information(self, "Sucesso", mensagem,
    QMessageBox.StandardButton.Ok)

  def cria_tela(self, FormularioAbastecimento) -> None:
    FormularioAbastecimento.setObjectName("FormularioAbastecimento")
    FormularioAbastecimento.resize(300, 202)
    self.ContainerForm = QtWidgets.QFrame(parent=FormularioAbastecimento)
    self.ContainerForm.setGeometry(QtCore.QRect(0, 0, 301, 201))
    self.ContainerForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerForm.setObjectName("ContainerForm")
    self.formLayout = QtWidgets.QFormLayout(self.ContainerForm)
    self.formLayout.setObjectName("formLayout")
    self.inputBomba = QtWidgets.QComboBox(parent=self.ContainerForm)
    self.inputBomba.setEnabled(True)
    self.inputBomba.setObjectName("inputBomba")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.inputBomba)
    self.label_2 = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
    self.label_2.setSizePolicy(sizePolicy)
    self.label_2.setObjectName("label_2")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
    self.label_3 = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
    self.label_3.setSizePolicy(sizePolicy)
    self.label_3.setObjectName("label_3")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
    self.inputTipo = QtWidgets.QComboBox(parent=self.ContainerForm)
    self.inputTipo.setEnabled(True)
    self.inputTipo.setObjectName("inputTipo")
    self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.inputTipo)
    self.label = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
    self.label.setSizePolicy(sizePolicy)
    self.label.setObjectName("label")
    self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
    self.label_4 = QtWidgets.QLabel(parent=self.ContainerForm)
    self.label_4.setObjectName("label_4")
    self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
    self.inputPreco = QtWidgets.QDoubleSpinBox(parent=self.ContainerForm)
    self.inputPreco.setMinimum(0.01)
    self.inputPreco.setMaximum(9999.99)
    self.inputPreco.setSingleStep(0.5)
    self.inputPreco.setObjectName("inputPreco")
    self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inputPreco)
    self.inputLitros = QtWidgets.QLineEdit(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.inputLitros.sizePolicy().hasHeightForWidth())
    self.inputLitros.setSizePolicy(sizePolicy)
    self.inputLitros.setReadOnly(True)
    self.inputLitros.setObjectName("inputLitros")
    self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputLitros)
    self.ContainerBotoes = QtWidgets.QFrame(parent=FormularioAbastecimento)
    self.ContainerBotoes.setGeometry(QtCore.QRect(0, 160, 301, 44))
    self.ContainerBotoes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBotoes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBotoes.setObjectName("ContainerBotoes")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContainerBotoes)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.cancelarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.cancelarBtn.setIcon(icon)
    self.cancelarBtn.setObjectName("Cancelar")
    self.horizontalLayout.addWidget(self.cancelarBtn)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.confirmarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.confirmarBtn.setIcon(icon1)
    self.confirmarBtn.setObjectName("Confirmar")
    self.horizontalLayout.addWidget(self.confirmarBtn)
    FormularioAbastecimento.setWindowTitle("Registrar Abastecimento")
    self.label_2.setText("Bomba *")
    self.label_3.setText("Tipo de combustivel *")
    self.label.setText("Litros abastecidos")
    self.label_4.setText("Preço *")
    self.cancelarBtn.setText("Cancelar")
    self.confirmarBtn.setText("Confirmar")
    QtCore.QMetaObject.connectSlotsByName(FormularioAbastecimento)