from src.abstract.TelaBase import TelaBase
from PyQt6 import QtWidgets, QtCore, QtGui
from PyQt6.QtWidgets import QLineEdit, QComboBox, QPushButton, QSpinBox

class TelaTanque(TelaBase):
  def __init__(self):
    super().__init__()
    self.inputId = QLineEdit()
    self.inputCapacidade = QLineEdit()
    self.inputPorcentagem = QSpinBox()
    self.inputTipo = QComboBox()
    self.confirmarBtn = QPushButton()
    self.cancelarBtn = QPushButton()
    self.cria_tela(self)

  def cria_tela(self, FormularioTanque) -> None:
    FormularioTanque.setObjectName("FormularioTanque")
    FormularioTanque.resize(300, 162)
    self.ContainerForm = QtWidgets.QFrame(parent=FormularioTanque)
    self.ContainerForm.setGeometry(QtCore.QRect(0, 10, 301, 151))
    self.ContainerForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerForm.setObjectName("ContainerForm")
    self.formLayout = QtWidgets.QFormLayout(self.ContainerForm)
    self.formLayout.setObjectName("formLayout")
    self.label = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
    self.label.setSizePolicy(sizePolicy)
    self.label.setObjectName("label")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
    self.inputId = QtWidgets.QLineEdit(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.inputId.sizePolicy().hasHeightForWidth())
    self.inputId.setSizePolicy(sizePolicy)
    self.inputId.setObjectName("inputId")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inputId)
    self.label_3 = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
    self.label_3.setSizePolicy(sizePolicy)
    self.label_3.setObjectName("label_3")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_3)
    self.inputPorcentagem = QtWidgets.QSpinBox(parent=self.ContainerForm)
    self.inputPorcentagem.setMinimum(1)
    self.inputPorcentagem.setObjectName("inputPorcentagem")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputPorcentagem)
    self.label_2 = QtWidgets.QLabel(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
    self.label_2.setSizePolicy(sizePolicy)
    self.label_2.setObjectName("label_2")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
    self.inputCapacidade = QtWidgets.QLineEdit(parent=self.ContainerForm)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.inputCapacidade.sizePolicy().hasHeightForWidth())
    self.inputCapacidade.setSizePolicy(sizePolicy)
    self.inputCapacidade.setObjectName("inputCapacidade")
    self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inputCapacidade)
    self.label_4 = QtWidgets.QLabel(parent=self.ContainerForm)
    self.label_4.setObjectName("label_4")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_4)
    self.inputTipo = QtWidgets.QComboBox(parent=self.ContainerForm)
    self.inputTipo.setEnabled(True)
    self.inputTipo.setObjectName("inputTipo")
    self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputTipo)
    self.ContainerBotoes = QtWidgets.QFrame(parent=FormularioTanque)
    self.ContainerBotoes.setGeometry(QtCore.QRect(0, 120, 301, 44))
    self.ContainerBotoes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBotoes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBotoes.setObjectName("ContainerBotoes")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContainerBotoes)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.cancelarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.cancelarBtn.setIcon(icon)
    self.cancelarBtn.setObjectName("Cancelar")
    self.horizontalLayout.addWidget(self.cancelarBtn)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.confirmarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.confirmarBtn.setIcon(icon1)
    self.confirmarBtn.setObjectName("Confirmar")
    self.horizontalLayout.addWidget(self.confirmarBtn)
    self.label.setText("ID do Tanque *")
    self.label_3.setText("Porcentagem de Alerta *")
    self.label_2.setText("Capacidade máxima (L) *")
    self.label_4.setText("Tipo de Combustível *")
    self.cancelarBtn.setText("Cancelar")
    self.confirmarBtn.setText("Confirmar")
    QtCore.QMetaObject.connectSlotsByName(FormularioTanque)