from src.abstract.TelaBase import TelaBase
from PyQt6 import QtWidgets, QtCore, QtGui
from PyQt6.QtWidgets import QLineEdit, QDoubleSpinBox, QPushButton

class TelaTipoCombustivel(TelaBase):
  def __init__(self):
    super().__init__()
    self.inputNome = QLineEdit()
    self.inputPreco = QDoubleSpinBox()
    self.confirmarBtn = QPushButton()
    self.cancelarBtn = QPushButton()
    self.cria_tela(self)

  def cria_tela(self, FormularioTipo) -> None:
    FormularioTipo.setObjectName("FormularioTipo")
    FormularioTipo.resize(260, 120)
    FormularioTipo.setMinimumSize(QtCore.QSize(260, 120))
    FormularioTipo.setMaximumSize(QtCore.QSize(260, 120))
    self.ContainerForm = QtWidgets.QFrame(parent=FormularioTipo)
    self.ContainerForm.setGeometry(QtCore.QRect(0, 10, 260, 60))
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ContainerForm.sizePolicy().hasHeightForWidth())
    self.ContainerForm.setSizePolicy(sizePolicy)
    self.ContainerForm.setMinimumSize(QtCore.QSize(260, 60))
    self.ContainerForm.setMaximumSize(QtCore.QSize(260, 60))
    self.ContainerForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerForm.setObjectName("ContainerForm")
    self.formLayout = QtWidgets.QFormLayout(self.ContainerForm)
    self.formLayout.setObjectName("formLayout")
    self.label = QtWidgets.QLabel(parent=self.ContainerForm)
    self.label.setObjectName("label")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
    self.label_2 = QtWidgets.QLabel(parent=self.ContainerForm)
    self.label_2.setObjectName("label_2")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
    self.inputNome = QtWidgets.QLineEdit(parent=self.ContainerForm)
    self.inputNome.setObjectName("inputNome")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inputNome)
    self.inputPreco = QtWidgets.QDoubleSpinBox(parent=self.ContainerForm)
    self.inputPreco.setMinimum(0.01)
    self.inputPreco.setSingleStep(0.5)
    self.inputPreco.setObjectName("inputPreco")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputPreco)
    self.ContainerBotoes = QtWidgets.QFrame(parent=FormularioTipo)
    self.ContainerBotoes.setGeometry(QtCore.QRect(0, 80, 261, 44))
    self.ContainerBotoes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBotoes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBotoes.setObjectName("ContainerBotoes")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContainerBotoes)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.cancelarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("./src/ui\\../../assets/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.cancelarBtn.setIcon(icon)
    self.cancelarBtn.setObjectName("Cancelar")
    self.horizontalLayout.addWidget(self.cancelarBtn)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.confirmarBtn = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("./src/ui\\../../assets/check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.confirmarBtn.setIcon(icon1)
    self.confirmarBtn.setObjectName("Confirmar")
    self.horizontalLayout.addWidget(self.confirmarBtn)
    FormularioTipo.setWindowTitle("Novo Tipo")
    self.label.setText("Nome")
    self.label_2.setText("Preço")
    self.cancelarBtn.setText("Cancelar")
    self.confirmarBtn.setText("Confirmar")
    QtCore.QMetaObject.connectSlotsByName(FormularioTipo)