from src.abstract.AbstractTela import AbstractTela
from PyQt6 import QtCore, QtGui, QtWidgets

class EscolherRegistrosComponent(AbstractTela):
  def __init__(self, entidade: str):
    super().__init__()
    self.entidade = entidade
    self.registros_data = self.carrega_dados(entidade=entidade)
    self.selecionados = []
    self.cria_tela(self)

  def open(self, selecionados_data: list) -> None:
    self.selecionados = selecionados_data
    self.fill_table(self.selecionados, self.tableRegistros)
    self.show()

  def confirmar(self) -> None:
    return

  def adicionar(self) -> None:
    selected_row = self.tableRegistros.currentRow()
    self.selecionados.append(self.registros_data[selected_row])
    self.fill_table(self.selecionados, self.tableSelecionados)

  def cria_tela(self, ComponentEscolherRegistros) -> None:
    ComponentEscolherRegistros.setObjectName("ComponentEscolherRegistros")
    ComponentEscolherRegistros.resize(602, 268)
    self.tableRegistros = QtWidgets.QTableWidget(parent=ComponentEscolherRegistros)
    self.tableRegistros.setGeometry(QtCore.QRect(10, 30, 241, 201))
    self.tableRegistros.setShowGrid(False)
    self.tableRegistros.setObjectName("tableRegistros")
    self.tableRegistros.setColumnCount(0)
    self.tableRegistros.setRowCount(0)
    self.tableRegistros.horizontalHeader().setDefaultSectionSize(135)
    self.tableRegistros.horizontalHeader().setSortIndicatorShown(True)
    self.tableRegistros.horizontalHeader().setStretchLastSection(True)
    self.tableSelecionados = QtWidgets.QTableWidget(parent=ComponentEscolherRegistros)
    self.tableSelecionados.setGeometry(QtCore.QRect(350, 30, 241, 201))
    self.tableSelecionados.setShowGrid(False)
    self.tableSelecionados.setObjectName("tableSelecionados")
    self.tableSelecionados.setColumnCount(0)
    self.tableSelecionados.setRowCount(0)
    self.tableSelecionados.horizontalHeader().setDefaultSectionSize(135)
    self.tableSelecionados.horizontalHeader().setSortIndicatorShown(True)
    self.tableSelecionados.horizontalHeader().setStretchLastSection(True)
    self.adicionarBtn = QtWidgets.QPushButton(parent=ComponentEscolherRegistros)
    self.adicionarBtn.setGeometry(QtCore.QRect(260, 90, 82, 24))
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.adicionarBtn.setIcon(icon)
    self.adicionarBtn.setObjectName("adicionarBtn")
    self.registrosLabel = QtWidgets.QLabel(parent=ComponentEscolherRegistros)
    self.registrosLabel.setGeometry(QtCore.QRect(10, 0, 142, 32))
    self.registrosLabel.setObjectName("registrosLabel")
    self.selecionadosLabel = QtWidgets.QLabel(parent=ComponentEscolherRegistros)
    self.selecionadosLabel.setGeometry(QtCore.QRect(350, 0, 142, 32))
    self.selecionadosLabel.setObjectName("selecionadosLabel")
    self.removerBtn = QtWidgets.QPushButton(parent=ComponentEscolherRegistros)
    self.removerBtn.setGeometry(QtCore.QRect(260, 120, 82, 24))
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.removerBtn.setIcon(icon1)
    self.removerBtn.setObjectName("removerBtn")
    self.ContainerBotoes = QtWidgets.QFrame(parent=ComponentEscolherRegistros)
    self.ContainerBotoes.setGeometry(QtCore.QRect(0, 230, 601, 44))
    self.ContainerBotoes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBotoes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBotoes.setObjectName("ContainerBotoes")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContainerBotoes)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.Cancelar = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.Cancelar.setIcon(icon2)
    self.Cancelar.setObjectName("Cancelar")
    self.horizontalLayout.addWidget(self.Cancelar)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.Confirmar = QtWidgets.QPushButton(parent=self.ContainerBotoes)
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../assets/check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.Confirmar.setIcon(icon3)
    self.Confirmar.setObjectName("Confirmar")
    self.horizontalLayout.addWidget(self.Confirmar)
    _translate = QtCore.QCoreApplication.translate
    ComponentEscolherRegistros.setWindowTitle(_translate("ComponentEscolherRegistros", "Escolher Registros"))
    self.tableRegistros.setSortingEnabled(True)
    self.tableSelecionados.setSortingEnabled(True)
    self.adicionarBtn.setText(_translate("ComponentEscolherRegistros", "Adicionar"))
    self.registrosLabel.setText(_translate("ComponentEscolherRegistros", "Registros:"))
    self.selecionadosLabel.setText(_translate("ComponentEscolherRegistros", "Selecionados:"))
    self.removerBtn.setText(_translate("ComponentEscolherRegistros", "Remover"))
    self.Cancelar.setText(_translate("ComponentEscolherRegistros", "Cancelar"))
    self.Confirmar.setText(_translate("ComponentEscolherRegistros", "Confirmar"))
    QtCore.QMetaObject.connectSlotsByName(ComponentEscolherRegistros)
    self.Confirmar.clicked.connect(self.confirmar)
    self.Cancelar.clicked.connect(self.cancelar)
    self.adicionarBtn.clicked.connect(self.adicionar) 
    self.removerBtn.clicked.connect() #####
    if self.entidade == 'tipos':
      self.tableRegistros.setColumnCount(2)
      self.tableRegistros.setRowCount(0)
      item = QtWidgets.QTableWidgetItem()
      item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
      self.tableRegistros.setHorizontalHeaderItem(0, item)
      item = QtWidgets.QTableWidgetItem()
      item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
      self.tableRegistros.setHorizontalHeaderItem(1, item)
      self.tableRegistros.horizontalHeader().setDefaultSectionSize(165)
      self.tableRegistros.horizontalHeader().setSortIndicatorShown(True)
      self.tableRegistros.horizontalHeader().setStretchLastSection(True)
      self.tableRegistros.setSortingEnabled(False)
      item = self.tableRegistros.horizontalHeaderItem(0)
      item.setText('Nome')
      item = self.tableRegistros.horizontalHeaderItem(1)
      item.setText('Preço (R$)')
      self.tableSelecionados.setColumnCount(2)
      self.tableSelecionados.setRowCount(0)
      item = QtWidgets.QTableWidgetItem()
      item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
      self.tableSelecionados.setHorizontalHeaderItem(0, item)
      item = QtWidgets.QTableWidgetItem()
      item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
      self.tableSelecionados.setHorizontalHeaderItem(1, item)
      self.tableSelecionados.horizontalHeader().setDefaultSectionSize(165)
      self.tableSelecionados.horizontalHeader().setSortIndicatorShown(True)
      self.tableSelecionados.horizontalHeader().setStretchLastSection(True)
      self.tableSelecionados.setSortingEnabled(False)
      item = self.tableSelecionados.horizontalHeaderItem(0)
      item.setText('Nome')
      item = self.tableSelecionados.horizontalHeaderItem(1)
      item.setText('Preço (R$)')
    self.fill_table(self.registros_data, self.tableRegistros)
