from src.abstract.TelaBase import TelaBase
from PyQt6 import QtCore, QtGui, QtWidgets
class InicialGlobal(QtWidgets.QMainWindow):
  def __init__(self):
    super().__init__()
    self.cria_tela(self)

  def iniciar_abastecimento(self) -> None:
    print(self.IniciarAbastecimento)

  def acessa_sistema(self) -> None:
    self.hide()
    from src.Login import Login
    self.login = Login()
    self.login.show()

  def cria_tela(self, InicialGlobal) -> None:
    InicialGlobal.setObjectName("InicialGlobal")
    InicialGlobal.resize(600, 400)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(InicialGlobal.sizePolicy().hasHeightForWidth())
    InicialGlobal.setSizePolicy(sizePolicy)
    InicialGlobal.setMinimumSize(QtCore.QSize(600, 400))
    InicialGlobal.setMaximumSize(QtCore.QSize(600, 400))
    InicialGlobal.setAutoFillBackground(False)
    InicialGlobal.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Portuguese, QtCore.QLocale.Country.Brazil))
    self.ContainerBtnIniciarAbastecimento = QtWidgets.QFrame(parent=InicialGlobal)
    self.ContainerBtnIniciarAbastecimento.setGeometry(QtCore.QRect(-1, -1, 600, 400))
    self.ContainerBtnIniciarAbastecimento.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBtnIniciarAbastecimento.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBtnIniciarAbastecimento.setObjectName("ContainerBtnIniciarAbastecimento")
    self.gridLayout = QtWidgets.QGridLayout(self.ContainerBtnIniciarAbastecimento)
    self.gridLayout.setContentsMargins(100, 100, 100, 100)
    self.gridLayout.setObjectName("gridLayout")
    self.IniciarAbastecimento = QtWidgets.QPushButton(parent=self.ContainerBtnIniciarAbastecimento)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.IniciarAbastecimento.sizePolicy().hasHeightForWidth())
    self.IniciarAbastecimento.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setBold(False)
    self.IniciarAbastecimento.setFont(font)
    self.IniciarAbastecimento.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(".\\telas\\../assets/bomba-combustivel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    self.IniciarAbastecimento.setIcon(icon)
    self.IniciarAbastecimento.setDefault(False)
    self.IniciarAbastecimento.setFlat(False)
    self.IniciarAbastecimento.setObjectName("IniciarAbastecimento")
    self.gridLayout.addWidget(self.IniciarAbastecimento, 0, 0, 1, 1)
    self.ContainerBtnAcessarSistema = QtWidgets.QFrame(parent=InicialGlobal)
    self.ContainerBtnAcessarSistema.setGeometry(QtCore.QRect(20, 360, 581, 44))
    self.ContainerBtnAcessarSistema.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    self.ContainerBtnAcessarSistema.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.ContainerBtnAcessarSistema.setObjectName("ContainerBtnAcessarSistema")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContainerBtnAcessarSistema)
    self.horizontalLayout.setObjectName("horizontalLayout")
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.AcessaSistema = QtWidgets.QPushButton(parent=self.ContainerBtnAcessarSistema)
    self.AcessaSistema.setObjectName("AcessaSistema")
    self.horizontalLayout.addWidget(self.AcessaSistema)
    InicialGlobal.setWindowTitle("GasGuardian")
    self.IniciarAbastecimento.setText("INICIAR ABASTECIMENTO")
    self.AcessaSistema.setText("Acessar Sistema")
    QtCore.QMetaObject.connectSlotsByName(InicialGlobal)
    self.IniciarAbastecimento.clicked.connect(self.iniciar_abastecimento)
    self.AcessaSistema.clicked.connect(self.acessa_sistema)
